#ifndef VA_PRIVATE_H
#define VA_PRIVATE_H

#define VA_MAX_PROFILES 24
#define VA_MAX_ENTRYPOINTS 2
#define VA_MAX_SUBPIC_FORMATS 1
#define VA_MAX_DISPLAY_ATTRIBS 1
#define VA_VENDOR_STRING "AMD libva driver"

#endif //VA_PRIVATE_H
